version: "3.8"

services:

  reverse-proxy:
    image: "traefik:v2.8.1" #"traefik:latest"
    container_name: "traefik"
    restart: unless-stopped #cela permet que le conteneur ne se lance pas à l'éxécution de docker desktop si le service est arrêté.
    command: #alternative est la création d'un fichier de config
      #- "--log.level=DEBUG"
      - "--api.insecure=true" #accés au dashboard
      - "--providers.docker=true" #déclaration de docker pour le backend
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80" #point d'entrée http
    ports:
      - "80:80"
      - "8181:8080" #modification de la redirection deja un containeur sur 8080 en local.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      #- "./traefik/traefik.yml:/etc/traefik/traefik.yml si besoin d'ajouter un fichier de config

  whoami1:
    image: "containous/whoami"
    container_name: "whoami1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.rule=Host(`first.localhost`)" #mapping dynamique 
      - "traefik.http.routers.whoami1.entrypoints=web"

  whoami2:
    image: "containous/whoami"
    container_name: "whoami2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`second.localhost`)" #mapping dynamique
      - "traefik.http.routers.whoami2.entrypoints=web"


