api:
  insecure: true

entryPoints:
    web:
      address: ':80'


providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"   
    exposedByDefault: false                   
    network: "traefik-benlab"                    
    watch: true                               
  file:
    filename: "/etc/traefik/config_dynamique/config.yml"  #Fichier de config dynamique
    watch: true                               
  

