http:
  routers:
    api:
      rule: "Host(`traefik.localhost`)"
      service: api@internal
      middlewares:
      - basic-auth
  middlewares:
    basic-auth:
      basicAuth:
        users:
          - "ben:$apr1$yN5SkU9i$/.72ViNpEiXNikGnMFNBV0" #ben 123456
        removeHeader: true
